#include "agent/telemetry/durable_spool.hpp"

#include <filesystem>
#include <stdexcept>
#include <chrono>
#include <algorithm>

#include <sqlite3.h>

#include "agent/internal/sqlite_utils.hpp"

namespace agent_framework::telemetry {
namespace { namespace sqlite=internal::sqlite;
nlohmann::json span_json(const SpanRecord&s){return{{"context",encode(s.context)},{"name",s.name},{"started_at",s.started_at},{"finished_at",s.finished_at},{"status",s.status},{"attributes",s.attributes}};}
SpanRecord span_value(const nlohmann::json&v){SpanRecord s;auto c=decode_correlation_context(v.at("context"));if(!c)throw std::runtime_error("invalid spooled span");s.context=std::move(*c);s.name=v.at("name");s.started_at=v.at("started_at");s.finished_at=v.at("finished_at");s.status=v.at("status");s.attributes=v.at("attributes").get<std::map<std::string,std::string>>();return s;}
nlohmann::json log_json(const LogRecord&v){return{{"context",encode(v.context)},{"timestamp",v.timestamp},{"severity",v.severity},{"body",v.body},{"attributes",v.attributes}};}
LogRecord log_value(const nlohmann::json&v){LogRecord l;auto c=decode_correlation_context(v.at("context"));if(!c)throw std::runtime_error("invalid spooled log");l.context=*c;l.timestamp=v.at("timestamp");l.severity=v.at("severity");l.body=v.at("body");l.attributes=v.at("attributes").get<std::map<std::string,std::string>>();return l;}
}
SQLiteTelemetrySpool::SQLiteTelemetrySpool(std::string path,std::shared_ptr<TelemetrySink> downstream,TelemetrySpoolOptions options):downstream_(std::move(downstream)),options_(std::move(options)){
    if(path.empty()||!downstream_||options_.maximum_attempts==0||options_.maximum_records==0)
        throw std::invalid_argument("valid spool path, downstream and limits are required");
    std::error_code ec;const std::filesystem::path file(path);if(file.has_parent_path())std::filesystem::create_directories(file.parent_path(),ec);sqlite3*opened=nullptr;if(ec||sqlite3_open_v2(path.c_str(),&opened,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK){const auto message=ec?ec.message():(opened?sqlite3_errmsg(opened):"sqlite open failed");if(opened)sqlite3_close(opened);throw std::runtime_error(message);}db_=opened;sqlite3_busy_timeout(opened,3000);sqlite::exec(opened,"PRAGMA journal_mode=WAL");sqlite::exec(opened,"PRAGMA synchronous=FULL");
    sqlite::exec(opened,"CREATE TABLE IF NOT EXISTS telemetry_spool(sequence INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,document_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL DEFAULT 0,next_attempt_ms INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT NOT NULL DEFAULT '',dead_letter INTEGER NOT NULL DEFAULT 0)");
    // Additive migration keeps COBS-era spool files recoverable.
    const auto add_column=[&](std::string_view ddl){char* message=nullptr;const auto rc=sqlite3_exec(opened,std::string(ddl).c_str(),nullptr,nullptr,&message);const std::string detail=message?message:"";if(message)sqlite3_free(message);if(rc!=SQLITE_OK&&detail.find("duplicate column name")==std::string::npos)throw std::runtime_error("telemetry spool migration failed: "+detail);};
    add_column("ALTER TABLE telemetry_spool ADD COLUMN created_at_ms INTEGER NOT NULL DEFAULT 0");
    add_column("ALTER TABLE telemetry_spool ADD COLUMN next_attempt_ms INTEGER NOT NULL DEFAULT 0");
    add_column("ALTER TABLE telemetry_spool ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0");
    add_column("ALTER TABLE telemetry_spool ADD COLUMN last_error TEXT NOT NULL DEFAULT ''");
    add_column("ALTER TABLE telemetry_spool ADD COLUMN dead_letter INTEGER NOT NULL DEFAULT 0");
}
SQLiteTelemetrySpool::~SQLiteTelemetrySpool(){if(db_)sqlite3_close(sqlite::database(db_));}
bool SQLiteTelemetrySpool::append(std::string_view kind,const nlohmann::json&document){auto*db=sqlite::database(db_);sqlite::Statement count(db,"SELECT COUNT(*) FROM telemetry_spool WHERE dead_letter=0");if(sqlite::step(count.get())!=SQLITE_ROW||static_cast<std::size_t>(sqlite::column_int64(count.get(),0))>=options_.maximum_records)return false;const auto now=options_.now_ms?options_.now_ms():static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());sqlite::Statement statement(db,"INSERT INTO telemetry_spool(kind,document_json,created_at_ms,next_attempt_ms) VALUES(?,?,?,?)");sqlite::bind_text(statement.get(),1,kind);sqlite::bind_text(statement.get(),2,document.dump());sqlite::bind_int64(statement.get(),3,static_cast<std::int64_t>(now));sqlite::bind_int64(statement.get(),4,static_cast<std::int64_t>(now));return sqlite::step(statement.get())==SQLITE_DONE;}
bool SQLiteTelemetrySpool::export_span(const SpanRecord&span){std::lock_guard lock(mutex_);return append("span",span_json(span));}
bool SQLiteTelemetrySpool::export_metric(const MetricResult&metric){std::lock_guard lock(mutex_);return append("metric",encode(metric));}
bool SQLiteTelemetrySpool::export_log(const LogRecord&log){std::lock_guard lock(mutex_);return append("log",log_json(log));}
bool SQLiteTelemetrySpool::flush(){std::lock_guard lock(mutex_);auto*db=sqlite::database(db_);const auto now=options_.now_ms?options_.now_ms():static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());{sqlite::Statement expire(db,"UPDATE telemetry_spool SET dead_letter=1,last_error='retention_expired' WHERE dead_letter=0 AND created_at_ms+?<?");sqlite::bind_int64(expire.get(),1,static_cast<std::int64_t>(options_.retention_ms));sqlite::bind_int64(expire.get(),2,static_cast<std::int64_t>(now));sqlite::step(expire.get());}sqlite::Statement query(db,"SELECT sequence,kind,document_json,attempts FROM telemetry_spool WHERE dead_letter=0 AND next_attempt_ms<=? ORDER BY sequence");sqlite::bind_int64(query.get(),1,static_cast<std::int64_t>(now));std::vector<std::int64_t> delivered;bool all=true;while(sqlite::step(query.get())==SQLITE_ROW){const auto sequence=sqlite::column_int64(query.get(),0);const auto kind=sqlite::column_text(query.get(),1);const auto attempts=static_cast<std::uint32_t>(sqlite::column_int64(query.get(),3));bool ok=false;try{const auto document=nlohmann::json::parse(sqlite::column_text(query.get(),2));if(kind=="span")ok=downstream_->export_span(span_value(document));else if(kind=="metric"){auto metric=decode_metric_result(document);ok=metric&&downstream_->export_metric(*metric);}else if(kind=="log")ok=downstream_->export_log(log_value(document));}catch(...){ok=false;}if(ok){delivered.push_back(sequence);continue;}all=false;const auto next_attempt=attempts+1;std::uint64_t backoff=options_.initial_backoff_ms;for(std::uint32_t i=1;i<next_attempt&&backoff<options_.maximum_backoff_ms;++i)backoff=std::min(options_.maximum_backoff_ms,backoff*2);sqlite::Statement retry(db,"UPDATE telemetry_spool SET attempts=?,next_attempt_ms=?,last_error='downstream_rejected',dead_letter=? WHERE sequence=?");sqlite::bind_int64(retry.get(),1,next_attempt);sqlite::bind_int64(retry.get(),2,static_cast<std::int64_t>(now+backoff));sqlite::bind_int64(retry.get(),3,next_attempt>=options_.maximum_attempts?1:0);sqlite::bind_int64(retry.get(),4,sequence);sqlite::step(retry.get());}if(!delivered.empty()&&!downstream_->flush())return false;if(!delivered.empty()){sqlite::Transaction transaction(db);sqlite::Statement erase(db,"DELETE FROM telemetry_spool WHERE sequence=?");for(const auto sequence:delivered){sqlite::bind_int64(erase.get(),1,sequence);if(sqlite::step(erase.get())!=SQLITE_DONE)return false;sqlite::reset(erase.get());sqlite::clear_bindings(erase.get());}transaction.commit();}return all;}
std::size_t SQLiteTelemetrySpool::pending()const{std::lock_guard lock(mutex_);auto*db=sqlite::database(db_);sqlite::Statement query(db,"SELECT COUNT(*) FROM telemetry_spool");return sqlite::step(query.get())==SQLITE_ROW?static_cast<std::size_t>(sqlite::column_int64(query.get(),0)):0;}
std::size_t SQLiteTelemetrySpool::dead_letters()const{std::lock_guard lock(mutex_);auto*db=sqlite::database(db_);sqlite::Statement query(db,"SELECT COUNT(*) FROM telemetry_spool WHERE dead_letter=1");return sqlite::step(query.get())==SQLITE_ROW?static_cast<std::size_t>(sqlite::column_int64(query.get(),0)):0;}
}  // namespace agent_framework::telemetry
