#include <cassert>
#include <chrono>
#include <filesystem>

#include "phase4_live_test_support.hpp"

int main(){using namespace phase4_live_test;auto e=environment("task-f7l-contract");auto m=matrix(e);assert(validate_live_contract(e,m).empty());assert(!role_environment_digest(e).empty());assert(!role_live_matrix_digest(m).empty());assert(decode_live_environment_profile(encode(e)));assert(decode_role_live_matrix(encode(m)));auto unknown=encode(e);unknown["payload"]["unknown"]=true;unknown["canonical_digest"]=contracts::embedded_digest(unknown).value();assert(!decode_live_environment_profile(unknown));auto nested=encode(m);nested["payload"]["cells"][0]["unknown"]=true;nested["canonical_digest"]=contracts::embedded_digest(nested).value();assert(!decode_role_live_matrix(nested));
    RoleCertificationCheckpoint cp;cp.metadata=e.metadata;cp.workflow_id="store-f7l";cp.environment_digest=role_environment_digest(e);cp.matrix_digest=role_live_matrix_digest(m);cp.updated_at="2026-08-10T00:00:00Z";assert(decode_role_certification_checkpoint(encode(cp)));InMemoryRoleCertificationStore memory;assert(memory.create(cp));auto next=cp;next.revision=2;next.next_cell=1;assert(memory.compare_exchange(next,1));assert(memory.compare_exchange(next,1).status==RoleCertificationStoreStatus::RevisionConflict);auto changed=next;changed.revision=3;changed.matrix_digest="sha256:changed";assert(memory.compare_exchange(changed,2).status==RoleCertificationStoreStatus::Invalid);
    auto suffix=std::to_string(std::chrono::steady_clock::now().time_since_epoch().count());auto path=(std::filesystem::temp_directory_path()/("taskflow-f7l-"+suffix+".sqlite")).string();{SQLiteRoleCertificationStore store(path);assert(store.create(cp));assert(store.compare_exchange(next,1));}{SQLiteRoleCertificationStore store(path);auto got=store.load("tenant-live","store-f7l");assert(got&&got->revision==2&&got->checkpoint.next_cell==1);}std::filesystem::remove(path);std::filesystem::remove(path+"-wal");std::filesystem::remove(path+"-shm");return 0;}
