#include "agent/tool_runtime/execution_control.hpp"
#include "agent/internal/sqlite_utils.hpp"
#include <sqlite3.h>
#include <stdexcept>
namespace agent_framework::tool_runtime {namespace s=agent_framework::internal::sqlite;
std::string_view name(CancellationStage v){static constexpr std::string_view n[]={"none","requested","cooperative","terminate","kill","reconciling","cancelled","manual_review"};return n[static_cast<int>(v)];}std::string_view name(BackpressureMode v){static constexpr std::string_view n[]={"block","drop_ephemeral","fail"};return n[static_cast<int>(v)];}
static CancellationStage stage(std::string_view v){for(int i=0;i<8;i++)if(name(static_cast<CancellationStage>(i))==v)return static_cast<CancellationStage>(i);return CancellationStage::ManualReview;}static BackpressureMode mode(std::string_view v){return v=="drop_ephemeral"?BackpressureMode::DropEphemeral:v=="fail"?BackpressureMode::Fail:BackpressureMode::Block;}
SQLiteExecutionControlStore::SQLiteExecutionControlStore(std::string p){if(sqlite3_open(p.c_str(),reinterpret_cast<sqlite3**>(&db_))!=SQLITE_OK)throw std::runtime_error("control store open failed");sqlite3_busy_timeout(s::database(db_),3000);migrate();}SQLiteExecutionControlStore::~SQLiteExecutionControlStore(){sqlite3_close(s::database(db_));}
void SQLiteExecutionControlStore::migrate(){s::exec(s::database(db_),"PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS agent_component_schema(component TEXT PRIMARY KEY,version INTEGER NOT NULL);INSERT OR IGNORE INTO agent_component_schema VALUES('execution_control',1);CREATE TABLE IF NOT EXISTS execution_controls(invocation_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,deadline_at_ms INTEGER NOT NULL,cancel_generation INTEGER NOT NULL DEFAULT 0,stage TEXT NOT NULL,revision INTEGER NOT NULL,reason TEXT NOT NULL,owner TEXT NOT NULL,fencing_token INTEGER NOT NULL,requested_at_ms INTEGER NOT NULL,next_escalation_at_ms INTEGER NOT NULL,lease_expires_at_ms INTEGER NOT NULL,effect_known INTEGER NOT NULL,receipt_digest TEXT NOT NULL,max_bytes INTEGER NOT NULL,max_events INTEGER NOT NULL,bp_mode TEXT NOT NULL,pending_bytes INTEGER NOT NULL DEFAULT 0,pending_events INTEGER NOT NULL DEFAULT 0);");s::Statement q(s::database(db_),"SELECT version FROM agent_component_schema WHERE component='execution_control'");if(s::step(q.get())!=SQLITE_ROW||s::column_int(q.get(),0)!=1)throw std::runtime_error("unsupported execution_control schema version");}
static CancellationIntent row(sqlite3_stmt*q){CancellationIntent x;x.control.invocation_id=s::column_text(q,0);x.control.tenant_id=s::column_text(q,1);x.control.deadline_at_ms=s::column_int64(q,2);x.control.cancel_generation=s::column_uint64(q,3);x.stage=stage(s::column_text(q,4));x.revision=s::column_uint64(q,5);x.reason=s::column_text(q,6);x.owner=s::column_text(q,7);x.fencing_token=s::column_uint64(q,8);x.requested_at_ms=s::column_int64(q,9);x.next_escalation_at_ms=s::column_int64(q,10);x.lease_expires_at_ms=s::column_int64(q,11);x.effect_known=s::column_int(q,12)!=0;x.receipt_digest=s::column_text(q,13);x.control.backpressure={s::column_uint64(q,14),s::column_uint64(q,15),mode(s::column_text(q,16))};return x;}
ControlResult SQLiteExecutionControlStore::create(const ExecutionControlEnvelope&v){std::scoped_lock l(mutex_);if(v.invocation_id.empty()||v.tenant_id.empty()||!v.backpressure.maximum_pending_bytes||!v.backpressure.maximum_pending_events)return {false,0,0,"invalid control envelope"};s::Statement q(s::database(db_),"INSERT OR IGNORE INTO execution_controls VALUES(?,?,?,0,'none',1,'','',0,0,0,0,0,'',?,?,?,0,0)");s::bind_text(q.get(),1,v.invocation_id);s::bind_text(q.get(),2,v.tenant_id);s::bind_int64(q.get(),3,v.deadline_at_ms);s::bind_uint64(q.get(),4,v.backpressure.maximum_pending_bytes);s::bind_uint64(q.get(),5,v.backpressure.maximum_pending_events);s::bind_text(q.get(),6,name(v.backpressure.mode));s::step(q.get());return {s::changes(s::database(db_))==1,1,0,s::changes(s::database(db_))?"":"already exists"};}
std::optional<CancellationIntent> SQLiteExecutionControlStore::load(std::string_view id){std::scoped_lock l(mutex_);s::Statement q(s::database(db_),"SELECT invocation_id,tenant_id,deadline_at_ms,cancel_generation,stage,revision,reason,owner,fencing_token,requested_at_ms,next_escalation_at_ms,lease_expires_at_ms,effect_known,receipt_digest,max_bytes,max_events,bp_mode FROM execution_controls WHERE invocation_id=?");s::bind_text(q.get(),1,id);return s::step(q.get())==SQLITE_ROW?std::optional(row(q.get())):std::nullopt;}
ControlResult SQLiteExecutionControlStore::request_cancel(std::string_view id,std::string reason,std::int64_t now){std::scoped_lock l(mutex_);s::Statement q(s::database(db_),"UPDATE execution_controls SET cancel_generation=cancel_generation+1,stage='requested',revision=revision+1,reason=?,requested_at_ms=?,next_escalation_at_ms=?,owner='',lease_expires_at_ms=0 WHERE invocation_id=? AND stage NOT IN('cancelled','manual_review')");s::bind_text(q.get(),1,reason);s::bind_int64(q.get(),2,now);s::bind_int64(q.get(),3,now);s::bind_text(q.get(),4,id);s::step(q.get());if(!s::changes(s::database(db_)))return {false,0,0,"not found or terminal"};s::Statement read(s::database(db_),"SELECT revision,cancel_generation FROM execution_controls WHERE invocation_id=?");s::bind_text(read.get(),1,id);s::step(read.get());return {true,s::column_uint64(read.get(),0),s::column_uint64(read.get(),1),{}};}
std::optional<CancellationIntent> SQLiteExecutionControlStore::claim(std::string_view id,std::string owner,std::int64_t now,std::int64_t lease){std::scoped_lock l(mutex_);s::Statement u(s::database(db_),"UPDATE execution_controls SET owner=?,fencing_token=fencing_token+1,lease_expires_at_ms=? WHERE invocation_id=? AND stage NOT IN('none','cancelled','manual_review') AND (owner='' OR lease_expires_at_ms<=? OR owner=?)");s::bind_text(u.get(),1,owner);s::bind_int64(u.get(),2,now+lease);s::bind_text(u.get(),3,id);s::bind_int64(u.get(),4,now);s::bind_text(u.get(),5,owner);s::step(u.get());if(!s::changes(s::database(db_)))return {};s::Statement q(s::database(db_),"SELECT invocation_id,tenant_id,deadline_at_ms,cancel_generation,stage,revision,reason,owner,fencing_token,requested_at_ms,next_escalation_at_ms,lease_expires_at_ms,effect_known,receipt_digest,max_bytes,max_events,bp_mode FROM execution_controls WHERE invocation_id=?");s::bind_text(q.get(),1,id);return s::step(q.get())==SQLITE_ROW?std::optional(row(q.get())):std::nullopt;}
ControlResult SQLiteExecutionControlStore::advance(std::string_view id,std::string_view owner,std::uint64_t fence,std::uint64_t expected,CancellationStage next,std::int64_t due,bool known,std::string receipt){std::scoped_lock l(mutex_);s::Statement q(s::database(db_),"UPDATE execution_controls SET stage=?,revision=revision+1,next_escalation_at_ms=?,effect_known=?,receipt_digest=? WHERE invocation_id=? AND owner=? AND fencing_token=? AND revision=?");s::bind_text(q.get(),1,name(next));s::bind_int64(q.get(),2,due);s::bind_int(q.get(),3,known);s::bind_text(q.get(),4,receipt);s::bind_text(q.get(),5,id);s::bind_text(q.get(),6,owner);s::bind_uint64(q.get(),7,fence);s::bind_uint64(q.get(),8,expected);s::step(q.get());return {s::changes(s::database(db_))==1,expected+1,0,s::changes(s::database(db_))?"":"fencing or revision conflict"};}
std::vector<CancellationIntent> SQLiteExecutionControlStore::recoverable(std::int64_t now,std::size_t limit){std::scoped_lock l(mutex_);s::Statement q(s::database(db_),"SELECT invocation_id,tenant_id,deadline_at_ms,cancel_generation,stage,revision,reason,owner,fencing_token,requested_at_ms,next_escalation_at_ms,lease_expires_at_ms,effect_known,receipt_digest,max_bytes,max_events,bp_mode FROM execution_controls WHERE stage NOT IN('none','cancelled','manual_review') AND next_escalation_at_ms<=? LIMIT ?");s::bind_int64(q.get(),1,now);s::bind_uint64(q.get(),2,limit);std::vector<CancellationIntent> out;while(s::step(q.get())==SQLITE_ROW)out.push_back(row(q.get()));return out;}
BackpressureReservation SQLiteExecutionControlStore::reserve(std::string_view id,std::uint64_t bytes,std::uint64_t events,bool ephemeral){std::scoped_lock l(mutex_);s::Statement q(s::database(db_),"SELECT max_bytes,max_events,bp_mode,pending_bytes,pending_events FROM execution_controls WHERE invocation_id=?");s::bind_text(q.get(),1,id);if(s::step(q.get())!=SQLITE_ROW)return {false,false,0,0,"control not found"};auto mb=s::column_uint64(q.get(),0),me=s::column_uint64(q.get(),1),pb=s::column_uint64(q.get(),3),pe=s::column_uint64(q.get(),4);auto m=mode(s::column_text(q.get(),2));if(bytes>mb-pb||events>me-pe){if(ephemeral&&m==BackpressureMode::DropEphemeral)return {false,true,pb,pe,{}};return {false,false,pb,pe,m==BackpressureMode::Block?"backpressure_blocked":"backpressure_limit_exceeded"};}s::Statement u(s::database(db_),"UPDATE execution_controls SET pending_bytes=pending_bytes+?,pending_events=pending_events+? WHERE invocation_id=?");s::bind_uint64(u.get(),1,bytes);s::bind_uint64(u.get(),2,events);s::bind_text(u.get(),3,id);s::step(u.get());return {true,false,pb+bytes,pe+events,{}};}
bool SQLiteExecutionControlStore::release(std::string_view id,std::uint64_t bytes,std::uint64_t events){std::scoped_lock l(mutex_);s::Statement u(s::database(db_),"UPDATE execution_controls SET pending_bytes=pending_bytes-?,pending_events=pending_events-? WHERE invocation_id=? AND pending_bytes>=? AND pending_events>=?");s::bind_uint64(u.get(),1,bytes);s::bind_uint64(u.get(),2,events);s::bind_text(u.get(),3,id);s::bind_uint64(u.get(),4,bytes);s::bind_uint64(u.get(),5,events);s::step(u.get());return s::changes(s::database(db_))==1;}
}
