#include "agent/tool_runtime/recovery_certification.hpp"
#include "agent/contracts/contract.hpp"
#include <random>
namespace agent_framework::tool_runtime {
std::string_view name(RecoveryEvidenceLevel v){static constexpr std::string_view n[]={"offline","process_live","provider_live"};return n[static_cast<int>(v)];}
std::string_view name(RecoveryScenario v){static constexpr std::string_view n[]={"worker_crash_takeover","stale_completion","cancel_before_start","cancel_complete_race","deadline_result_race","cancel_restart_escalation","object_corruption","missing_object","sqlite_busy","storage_failure","schema_migration","provider_disconnect","provider_reattach"};return n[static_cast<int>(v)];}
std::vector<RecoveryScenario> mandatory_recovery_scenarios(){return {RecoveryScenario::WorkerCrashTakeover,RecoveryScenario::StaleCompletion,RecoveryScenario::CancelBeforeStart,RecoveryScenario::CancelCompleteRace,RecoveryScenario::DeadlineResultRace,RecoveryScenario::CancelRestartEscalation,RecoveryScenario::ObjectCorruption,RecoveryScenario::MissingObject,RecoveryScenario::SqliteBusy,RecoveryScenario::StorageFailure,RecoveryScenario::SchemaMigration,RecoveryScenario::ProviderDisconnect,RecoveryScenario::ProviderReattach};}
RecoveryCertificationReport certify_recovery(std::string environment,RecoveryEvidenceLevel available,const RecoveryScenarioExecutor& execute){RecoveryCertificationReport r;r.environment_digest=std::move(environment);for(auto scenario:mandatory_recovery_scenarios()){RecoveryCell c;c.scenario=scenario;c.required_level=(scenario==RecoveryScenario::ProviderDisconnect||scenario==RecoveryScenario::ProviderReattach)?RecoveryEvidenceLevel::ProviderLive:scenario==RecoveryScenario::WorkerCrashTakeover?RecoveryEvidenceLevel::ProcessLive:RecoveryEvidenceLevel::Offline;if(static_cast<int>(available)<static_cast<int>(c.required_level)){c.reason="required evidence level unavailable";}else if(execute)c=execute(scenario);c.scenario=scenario;c.required_level=(scenario==RecoveryScenario::ProviderDisconnect||scenario==RecoveryScenario::ProviderReattach)?RecoveryEvidenceLevel::ProviderLive:scenario==RecoveryScenario::WorkerCrashTakeover?RecoveryEvidenceLevel::ProcessLive:RecoveryEvidenceLevel::Offline;if(!c.executed)r.blockers.push_back(std::string(name(scenario))+":required_not_executed");else if(!c.passed)r.blockers.push_back(std::string(name(scenario))+":failed:"+c.reason);else if(c.evidence_digest.empty())r.blockers.push_back(std::string(name(scenario))+":missing_evidence");r.cells.push_back(std::move(c));}if(r.environment_digest.empty())r.blockers.push_back("environment_digest_missing");r.certified=r.blockers.empty();return r;}
nlohmann::json encode(const RecoveryCertificationReport&r){nlohmann::json cells=nlohmann::json::array();for(const auto&c:r.cells)cells.push_back({{"scenario",name(c.scenario)},{"required_level",name(c.required_level)},{"required",c.required},{"executed",c.executed},{"passed",c.passed},{"reason",c.reason},{"evidence_digest",c.evidence_digest},{"operations",c.operations},{"failures",c.failures}});return {{"matrix_revision",r.matrix_revision},{"environment_digest",r.environment_digest},{"cells",cells},{"blockers",r.blockers},{"certified",r.certified}};}
SoakReport run_recovery_soak(const SoakOptions&o,const SoakOperation&fn){SoakReport r;r.iterations=o.iterations;r.seed=o.seed;r.concurrency=o.concurrency;if(!o.iterations||!o.concurrency||!fn){r.failures=1;return r;}std::mt19937_64 random(o.seed);for(std::uint64_t i=0;i<o.iterations;i++){r.operations++;if(fn(i,random()))r.recoveries++;else r.failures++;}r.passed=r.failures==0;auto value=nlohmann::json{{"iterations",r.iterations},{"operations",r.operations},{"recoveries",r.recoveries},{"failures",r.failures},{"seed",r.seed},{"concurrency",r.concurrency},{"passed",r.passed}};r.evidence_digest=contracts::canonical_digest(value).value_or("");return r;}
}
