#include "agent/agent_template/runner.hpp"
#include "agent/contracts/contract.hpp"
#include <stdexcept>
namespace agent_framework::agent_template {
namespace { RunnerEvent event(const RunnerRequest&r,std::uint64_t seq,RunnerLifecycleState state,nlohmann::json details={}){return{r.invocation.invocation_id+":"+r.node.node_id+":"+std::to_string(seq),seq,r.node.node_id,state,"",std::move(details)};} }
CallbackSkillRunner::CallbackSkillRunner(SkillRunnerKind k,RunnerCallback c):kind_(k),callback_(std::move(c)){if(!callback_)throw std::invalid_argument("runner callback required");}
RunnerResult CallbackSkillRunner::run(const RunnerRequest&r){RunnerResult out;out.receipt.invocation_id=r.invocation.invocation_id;out.receipt.node_id=r.node.node_id;out.receipt.runner=kind_;auto cancel=r.cancel?r.cancel:std::make_shared<std::atomic_bool>(false);{std::lock_guard l(mutex_);active_[r.invocation.invocation_id+":"+r.node.node_id]=cancel;}out.events={event(r,1,RunnerLifecycleState::Admitted),event(r,2,RunnerLifecycleState::Prepared),event(r,3,RunnerLifecycleState::Running)};try{if(cancel->load())throw std::runtime_error("cancelled");out.output=callback_(r);if(cancel->load())throw std::runtime_error("cancelled");out.ok=true;out.receipt.terminal_state=RunnerLifecycleState::Succeeded;out.receipt.output_digest=contracts::embedded_digest(out.output).value_or("");out.events.push_back(event(r,4,RunnerLifecycleState::Succeeded,{{"output_digest",out.receipt.output_digest}}));}catch(const std::exception&e){out.error_message=e.what();out.error_code=cancel->load()?"cancelled":"runner_failed";out.receipt.terminal_state=cancel->load()?RunnerLifecycleState::Cancelled:RunnerLifecycleState::Failed;out.events.push_back(event(r,4,out.receipt.terminal_state,{{"error",out.error_message}}));}{std::lock_guard l(mutex_);active_.erase(r.invocation.invocation_id+":"+r.node.node_id);}return out;}
bool CallbackSkillRunner::cancel(std::string_view id){std::lock_guard l(mutex_);auto i=active_.find(std::string(id));if(i==active_.end())return false;i->second->store(true);return true;}
bool SkillRunnerRegistry::register_runner(std::shared_ptr<SkillRunner>r){if(!r)return false;std::lock_guard l(mutex_);return runners_.emplace(r->kind(),std::move(r)).second;}std::shared_ptr<SkillRunner> SkillRunnerRegistry::resolve(SkillRunnerKind k)const{std::lock_guard l(mutex_);auto i=runners_.find(k);return i==runners_.end()?nullptr:i->second;}
}
